version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    groups:
      development:
        dependency-type: 'development'
        patterns:
          - '*'
      production:
        dependency-type: 'production'
        patterns:
          - '*'
